### ISSUE TITLE
v1.2 Bugs

### ISSUE THREAD

**Issue by Cram-o-dev** [Cram-o-dev/cramorantedition#5]
Please state any bugs you encounter here and I will look into them.

**Comment by Cram-o-dev** [comment]
When building the Rom from the repo, the title screen colors are messed up but the rest of the game works fine. Need to look into this.

**Comment by Pandemoniu** [comment]
In the documentation spreadsheet, Mega Punch is listed a Fighting-type move.

However, in the game, when selecting the move in a battle, Mega Punch is still listed as being the canon's Normal-type. It's also still doing Normal-type damage.

I was quite excited to find Mega Punch and Mega Kick being made Fighting, since the game lacks strong damage-dealing Fighting-type moves. With Mega Punch's bug, however, that turned out to be an unfortunate waste of a TM. It makes me wonder if Mega Kick is bugged, too.

EDIT: Looking into the folders and files in the repository, it does indeed seem that Mega Kick is also Normal instead of Fighting like the spreadsheet suggests.

**Comment by Pandemoniu** [comment]
Wild Marowak on the 6th Floor of Pokémon Tower are treated as if they were the scripted Marowak by the upward stairs. This includes "being identified by the Silph Scope", despite not actually being hidden, and most notably not being able to be captured like the scripted Marowak.

**Comment by Cram-o-dev** [comment]
Thanks for letting me know about these. Been very busy but will eventually get to fixing these. And yes, Mega Punch and Kick are supposed to be normal, just an error on my part.

**Comment by Pandemoniu** [comment]
> Thanks for letting me know about these. Been very busy but will eventually get to fixing these. And yes, Mega Punch and Kick are supposed to be normal, just an error on my part.

You're welcome!

Not gonna lie; would love for more easily accessible Fighting moves, which Gen 1 sorely lacks.

**Comment by DarianTrinity** [comment]
This'll probably be low priority since you would have to go out of your way to do this glitch, but the Pikawalk (off-screen Pikachu) glitch still exists and might trip some players up if they don't know what they're doing somehow
Info can be found here https://archives.glitchcity.info/wiki/Pikachu_off-screen_glitch.html

**Comment by Cram-o-dev** [comment]
Closing this for a spot for version 1.4 bugs.
